/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type MembershipInformation = {
    _type: 'membershipInformation';
    members?: string;
    inhabitants?: string;
    population?: string;
    natives?: string;
};

export type AppearanceInformation = {
    _type: 'appearanceInformation';
    gender?: string;
    appearance?: string;
    properties?: string;
    size?: string;
    shape?: string;
    traits?: string;
    race?: string;
    age?: string;
    averageLifespan?: string;
    distinctions?: string;
};

export type RelationalInformation = {
    _type: 'relationalInformation';
    participants?: string;
    leadership?: string;
    allies?: string;
    enemies?: string;
    allegiance?: string;
    familyClan?: string;
    connections?: string;
};

export type HistoricalInformation = {
    _type: 'historicalInformation';
    origin?: string;
    creator?: string;
    responsibleParties?: string;
    outcome?: string;
};

export type DivineInformation = {
    _type: 'divineInformation';
    alignment?: string;
    provinces?: string;
};

export type CommerceInformation = {
    _type: 'commerceInformation';
    imports?: string;
    exports?: string;
    currency?: string;
};

export type GeographicalInformation = {
    _type: 'geographicalInformation';
    location?: string;
    region?: string;
    plane?: string;
    pointsOfInterest?: string;
    colorPool?: string;
    gravity?: string;
    time?: string;
    capital?: string;
    politicalType?: string;
};

export type DateInformation = {
    _type: 'dateInformation';
    date?: string;
    established?: string;
    abolished?: string;
    born?: string;
    died?: string;
};

export type BasicInformation = {
    _type: 'basicInformation';
    type?: string;
    titles?: string;
    symbol?: string;
    demonym?: string;
    variants?: string;
    languages?: string;
    occupation?: string;
    environment?: string;
    diet?: string;
    notableStatistics?: string;
    usage?: string;
};

export type ExternalLink = {
    _type: 'externalLink';
    url?: string;
    newWindow?: boolean;
};

export type InternalLink = {
    _type: 'internalLink';
    reference?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'god';
    };
};

export type Content = Array<
    | {
          asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: 'image';
          _key: string;
      }
    | {
          children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
          }>;
          style?: 'normal' | 'h2' | 'blockquote';
          listItem?: 'bullet' | 'number';
          markDefs?: Array<
              | {
                    reference?: {
                        _ref: string;
                        _type: 'reference';
                        _weak?: boolean;
                        [internalGroqTypeReferenceTo]?: 'god';
                    };
                    _type: 'internalLink';
                    _key: string;
                }
              | {
                    url?: string;
                    newWindow?: boolean;
                    _type: 'externalLink';
                    _key: string;
                }
          >;
          level?: number;
          _type: 'block';
          _key: string;
      }
>;

export type Writing = {
    _id: string;
    _type: 'writing';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    writingType?: 'myth' | 'story' | 'poem';
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    content?: Content;
};

export type Region = {
    _id: string;
    _type: 'region';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    geography?: Content;
    inhabitants?: Content;
    society?: Content;
    trade?: Content;
    history?: Content;
    notableLocations?: Content;
};

export type Plane = {
    _id: string;
    _type: 'plane';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    layers?: Content;
    inhabitants?: Content;
    history?: Content;
    cosmography?: Content;
    locations?: Content;
};

export type Person = {
    _id: string;
    _type: 'person';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    appearance?: Content;
    history?: Content;
    relationships?: Content;
    personality?: Content;
    abilities?: Content;
};

export type Organization = {
    _id: string;
    _type: 'organization';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    goals?: Content;
    baseOfOperations?: Content;
    history?: Content;
    activities?: Content;
};

export type Lineage = {
    _id: string;
    _type: 'lineage';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    appearance?: Content;
    abilities?: Content;
    habitat?: Content;
    cultures?: Content;
    society?: Content;
    history?: Content;
};

export type Landmark = {
    _id: string;
    _type: 'landmark';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    history?: Content;
    geography?: Content;
    myths?: Content;
};

export type HistoricalEvent = {
    _id: string;
    _type: 'historicalEvent';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    events?: Content;
    consequences?: Content;
    etymology?: Content;
};

export type Flora = {
    _id: string;
    _type: 'flora';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    variants?: Content;
    habitat?: Content;
    usage?: Content;
    history?: Content;
};

export type Entity = {
    _id: string;
    _type: 'entity';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    usage?: Content;
    appearance?: Content;
};

export type Creature = {
    _id: string;
    _type: 'creature';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    behavior?: Content;
    abilities?: Content;
    ecology?: Content;
    biology?: Content;
    combat?: Content;
    subspecies?: Content;
    history?: Content;
    society?: Content;
    usage?: Content;
};

export type Concept = {
    _id: string;
    _type: 'concept';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    history?: Content;
    variations?: Content;
    usage?: Content;
};

export type City = {
    _id: string;
    _type: 'city';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
    society?: Content;
    government?: Content;
    districts?: Content;
    history?: Content;
    organizations?: Content;
};

export type Artwork = {
    _id: string;
    _type: 'artwork';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    description?: Content;
};

export type God = {
    _id: string;
    _type: 'god';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    defaultAttributes?: DefaultAttributes;
    information?: Information;
    appearance?: Content;
    teachings?: Content;
    symbology?: Content;
    history?: Content;
    relations?: Content;
    religion?: Content;
};

export type DefaultAttributes = {
    _type: 'defaultAttributes';
    slug?: Slug;
    name?: string;
    shortDescription?: Content;
    altNames?: Array<string>;
    image?: {
        asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
    };
    tags?: Array<string>;
    appendix?: Content;
};

export type DocumentSettings = {
    _id: string;
    _type: 'documentSettings';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    information?: Information;
    informationCategories?: {
        basics?: string;
        dates?: string;
        geography?: string;
        commerce?: string;
        divinity?: string;
        history?: string;
        relations?: string;
        appearance?: string;
        membership?: string;
    };
};

export type Information = {
    _type: 'information';
    basics?: BasicInformation;
    dates?: DateInformation;
    geography?: GeographicalInformation;
    commerce?: CommerceInformation;
    divinity?: DivineInformation;
    history?: HistoricalInformation;
    relations?: RelationalInformation;
    appearance?: AppearanceInformation;
    membership?: MembershipInformation;
};

export type MediaTag = {
    _id: string;
    _type: 'media.tag';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: Slug;
};

export type SanityImagePaletteSwatch = {
    _type: 'sanity.imagePaletteSwatch';
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: 'sanity.imagePalette';
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: 'sanity.imageDimensions';
    height?: number;
    width?: number;
    aspectRatio?: number;
};

export type SanityImageHotspot = {
    _type: 'sanity.imageHotspot';
    x?: number;
    y?: number;
    height?: number;
    width?: number;
};

export type SanityImageCrop = {
    _type: 'sanity.imageCrop';
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
};

export type SanityFileAsset = {
    _id: string;
    _type: 'sanity.fileAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
    _id: string;
    _type: 'sanity.imageAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
    _type: 'sanity.imageMetadata';
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type Geopoint = {
    _type: 'geopoint';
    lat?: number;
    lng?: number;
    alt?: number;
};

export type Slug = {
    _type: 'slug';
    current?: string;
    source?: string;
};

export type SanityAssetSourceData = {
    _type: 'sanity.assetSourceData';
    name?: string;
    id?: string;
    url?: string;
};

export type AllSanitySchemaTypes =
    | MembershipInformation
    | AppearanceInformation
    | RelationalInformation
    | HistoricalInformation
    | DivineInformation
    | CommerceInformation
    | GeographicalInformation
    | DateInformation
    | BasicInformation
    | ExternalLink
    | InternalLink
    | Content
    | Writing
    | Region
    | Plane
    | Person
    | Organization
    | Lineage
    | Landmark
    | HistoricalEvent
    | Flora
    | Entity
    | Creature
    | Concept
    | City
    | Artwork
    | God
    | DefaultAttributes
    | DocumentSettings
    | Information
    | MediaTag
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageHotspot
    | SanityImageCrop
    | SanityFileAsset
    | SanityImageAsset
    | SanityImageMetadata
    | Geopoint
    | Slug
    | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./../frontend/src/queries/pages/queries.ts
// Variable: documentSettings
// Query: *[ _type == 'documentSettings' ][0]{ information, informationCategories }
export type DocumentSettingsResult = {
    information: Information | null;
    informationCategories: {
        basics?: string;
        dates?: string;
        geography?: string;
        commerce?: string;
        divinity?: string;
        history?: string;
        relations?: string;
        appearance?: string;
        membership?: string;
    } | null;
} | null;

// Source: ./../frontend/src/queries/products/queries.ts
// Variable: specificTypePageQuery
// Query: *[_type == $type && defaultAttributes.slug.current == $name][0]
export type SpecificTypePageQueryResult =
    | {
          _id: string;
          _type: 'artwork';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
      }
    | {
          _id: string;
          _type: 'city';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          society?: Content;
          government?: Content;
          districts?: Content;
          history?: Content;
          organizations?: Content;
      }
    | {
          _id: string;
          _type: 'concept';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          history?: Content;
          variations?: Content;
          usage?: Content;
      }
    | {
          _id: string;
          _type: 'creature';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          behavior?: Content;
          abilities?: Content;
          ecology?: Content;
          biology?: Content;
          combat?: Content;
          subspecies?: Content;
          history?: Content;
          society?: Content;
          usage?: Content;
      }
    | {
          _id: string;
          _type: 'documentSettings';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          information?: Information;
          informationCategories?: {
              basics?: string;
              dates?: string;
              geography?: string;
              commerce?: string;
              divinity?: string;
              history?: string;
              relations?: string;
              appearance?: string;
              membership?: string;
          };
      }
    | {
          _id: string;
          _type: 'entity';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          usage?: Content;
          appearance?: Content;
      }
    | {
          _id: string;
          _type: 'flora';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          variants?: Content;
          habitat?: Content;
          usage?: Content;
          history?: Content;
      }
    | {
          _id: string;
          _type: 'god';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          appearance?: Content;
          teachings?: Content;
          symbology?: Content;
          history?: Content;
          relations?: Content;
          religion?: Content;
      }
    | {
          _id: string;
          _type: 'historicalEvent';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          events?: Content;
          consequences?: Content;
          etymology?: Content;
      }
    | {
          _id: string;
          _type: 'landmark';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          history?: Content;
          geography?: Content;
          myths?: Content;
      }
    | {
          _id: string;
          _type: 'lineage';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          appearance?: Content;
          abilities?: Content;
          habitat?: Content;
          cultures?: Content;
          society?: Content;
          history?: Content;
      }
    | {
          _id: string;
          _type: 'media.tag';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          name?: Slug;
      }
    | {
          _id: string;
          _type: 'organization';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          goals?: Content;
          baseOfOperations?: Content;
          history?: Content;
          activities?: Content;
      }
    | {
          _id: string;
          _type: 'person';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          appearance?: Content;
          history?: Content;
          relationships?: Content;
          personality?: Content;
          abilities?: Content;
      }
    | {
          _id: string;
          _type: 'plane';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          layers?: Content;
          inhabitants?: Content;
          history?: Content;
          cosmography?: Content;
          locations?: Content;
      }
    | {
          _id: string;
          _type: 'region';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          geography?: Content;
          inhabitants?: Content;
          society?: Content;
          trade?: Content;
          history?: Content;
          notableLocations?: Content;
      }
    | {
          _id: string;
          _type: 'sanity.fileAsset';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          source?: SanityAssetSourceData;
      }
    | {
          _id: string;
          _type: 'sanity.imageAsset';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
      }
    | {
          _id: string;
          _type: 'writing';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          writingType?: 'myth' | 'poem' | 'story';
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          content?: Content;
      }
    | null;
// Variable: specificWritingTypePageQuery
// Query: *[_type == $type && writingType == $writingType && defaultAttributes.slug.current == $name][0]
export type SpecificWritingTypePageQueryResult =
    | {
          _id: string;
          _type: 'artwork';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
      }
    | {
          _id: string;
          _type: 'city';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          society?: Content;
          government?: Content;
          districts?: Content;
          history?: Content;
          organizations?: Content;
      }
    | {
          _id: string;
          _type: 'concept';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          history?: Content;
          variations?: Content;
          usage?: Content;
      }
    | {
          _id: string;
          _type: 'creature';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          behavior?: Content;
          abilities?: Content;
          ecology?: Content;
          biology?: Content;
          combat?: Content;
          subspecies?: Content;
          history?: Content;
          society?: Content;
          usage?: Content;
      }
    | {
          _id: string;
          _type: 'documentSettings';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          information?: Information;
          informationCategories?: {
              basics?: string;
              dates?: string;
              geography?: string;
              commerce?: string;
              divinity?: string;
              history?: string;
              relations?: string;
              appearance?: string;
              membership?: string;
          };
      }
    | {
          _id: string;
          _type: 'entity';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          usage?: Content;
          appearance?: Content;
      }
    | {
          _id: string;
          _type: 'flora';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          variants?: Content;
          habitat?: Content;
          usage?: Content;
          history?: Content;
      }
    | {
          _id: string;
          _type: 'god';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          appearance?: Content;
          teachings?: Content;
          symbology?: Content;
          history?: Content;
          relations?: Content;
          religion?: Content;
      }
    | {
          _id: string;
          _type: 'historicalEvent';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          events?: Content;
          consequences?: Content;
          etymology?: Content;
      }
    | {
          _id: string;
          _type: 'landmark';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          history?: Content;
          geography?: Content;
          myths?: Content;
      }
    | {
          _id: string;
          _type: 'lineage';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          appearance?: Content;
          abilities?: Content;
          habitat?: Content;
          cultures?: Content;
          society?: Content;
          history?: Content;
      }
    | {
          _id: string;
          _type: 'media.tag';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          name?: Slug;
      }
    | {
          _id: string;
          _type: 'organization';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          goals?: Content;
          baseOfOperations?: Content;
          history?: Content;
          activities?: Content;
      }
    | {
          _id: string;
          _type: 'person';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          appearance?: Content;
          history?: Content;
          relationships?: Content;
          personality?: Content;
          abilities?: Content;
      }
    | {
          _id: string;
          _type: 'plane';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          layers?: Content;
          inhabitants?: Content;
          history?: Content;
          cosmography?: Content;
          locations?: Content;
      }
    | {
          _id: string;
          _type: 'region';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          geography?: Content;
          inhabitants?: Content;
          society?: Content;
          trade?: Content;
          history?: Content;
          notableLocations?: Content;
      }
    | {
          _id: string;
          _type: 'sanity.fileAsset';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          source?: SanityAssetSourceData;
      }
    | {
          _id: string;
          _type: 'sanity.imageAsset';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
      }
    | {
          _id: string;
          _type: 'writing';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          writingType?: 'myth' | 'poem' | 'story';
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          content?: Content;
      }
    | null;
// Variable: allProductsOfType
// Query: *[_type == $type && defined(defaultAttributes.slug.current)]
export type AllProductsOfTypeResult = Array<
    | {
          _id: string;
          _type: 'artwork';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
      }
    | {
          _id: string;
          _type: 'city';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          society?: Content;
          government?: Content;
          districts?: Content;
          history?: Content;
          organizations?: Content;
      }
    | {
          _id: string;
          _type: 'concept';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          history?: Content;
          variations?: Content;
          usage?: Content;
      }
    | {
          _id: string;
          _type: 'creature';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          behavior?: Content;
          abilities?: Content;
          ecology?: Content;
          biology?: Content;
          combat?: Content;
          subspecies?: Content;
          history?: Content;
          society?: Content;
          usage?: Content;
      }
    | {
          _id: string;
          _type: 'entity';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          usage?: Content;
          appearance?: Content;
      }
    | {
          _id: string;
          _type: 'flora';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          variants?: Content;
          habitat?: Content;
          usage?: Content;
          history?: Content;
      }
    | {
          _id: string;
          _type: 'god';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          appearance?: Content;
          teachings?: Content;
          symbology?: Content;
          history?: Content;
          relations?: Content;
          religion?: Content;
      }
    | {
          _id: string;
          _type: 'historicalEvent';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          events?: Content;
          consequences?: Content;
          etymology?: Content;
      }
    | {
          _id: string;
          _type: 'landmark';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          history?: Content;
          geography?: Content;
          myths?: Content;
      }
    | {
          _id: string;
          _type: 'lineage';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          appearance?: Content;
          abilities?: Content;
          habitat?: Content;
          cultures?: Content;
          society?: Content;
          history?: Content;
      }
    | {
          _id: string;
          _type: 'organization';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          goals?: Content;
          baseOfOperations?: Content;
          history?: Content;
          activities?: Content;
      }
    | {
          _id: string;
          _type: 'person';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          appearance?: Content;
          history?: Content;
          relationships?: Content;
          personality?: Content;
          abilities?: Content;
      }
    | {
          _id: string;
          _type: 'plane';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          layers?: Content;
          inhabitants?: Content;
          history?: Content;
          cosmography?: Content;
          locations?: Content;
      }
    | {
          _id: string;
          _type: 'region';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          geography?: Content;
          inhabitants?: Content;
          society?: Content;
          trade?: Content;
          history?: Content;
          notableLocations?: Content;
      }
    | {
          _id: string;
          _type: 'writing';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          writingType?: 'myth' | 'poem' | 'story';
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          content?: Content;
      }
>;
// Variable: allWritingProductsOfType
// Query: *[_type == $type && writingType == $writingType && defined(defaultAttributes.slug.current) ]
export type AllWritingProductsOfTypeResult = Array<
    | {
          _id: string;
          _type: 'artwork';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
      }
    | {
          _id: string;
          _type: 'city';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          society?: Content;
          government?: Content;
          districts?: Content;
          history?: Content;
          organizations?: Content;
      }
    | {
          _id: string;
          _type: 'concept';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          history?: Content;
          variations?: Content;
          usage?: Content;
      }
    | {
          _id: string;
          _type: 'creature';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          behavior?: Content;
          abilities?: Content;
          ecology?: Content;
          biology?: Content;
          combat?: Content;
          subspecies?: Content;
          history?: Content;
          society?: Content;
          usage?: Content;
      }
    | {
          _id: string;
          _type: 'entity';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          usage?: Content;
          appearance?: Content;
      }
    | {
          _id: string;
          _type: 'flora';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          variants?: Content;
          habitat?: Content;
          usage?: Content;
          history?: Content;
      }
    | {
          _id: string;
          _type: 'god';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          appearance?: Content;
          teachings?: Content;
          symbology?: Content;
          history?: Content;
          relations?: Content;
          religion?: Content;
      }
    | {
          _id: string;
          _type: 'historicalEvent';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          events?: Content;
          consequences?: Content;
          etymology?: Content;
      }
    | {
          _id: string;
          _type: 'landmark';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          history?: Content;
          geography?: Content;
          myths?: Content;
      }
    | {
          _id: string;
          _type: 'lineage';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          appearance?: Content;
          abilities?: Content;
          habitat?: Content;
          cultures?: Content;
          society?: Content;
          history?: Content;
      }
    | {
          _id: string;
          _type: 'organization';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          goals?: Content;
          baseOfOperations?: Content;
          history?: Content;
          activities?: Content;
      }
    | {
          _id: string;
          _type: 'person';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          appearance?: Content;
          history?: Content;
          relationships?: Content;
          personality?: Content;
          abilities?: Content;
      }
    | {
          _id: string;
          _type: 'plane';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          layers?: Content;
          inhabitants?: Content;
          history?: Content;
          cosmography?: Content;
          locations?: Content;
      }
    | {
          _id: string;
          _type: 'region';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          geography?: Content;
          inhabitants?: Content;
          society?: Content;
          trade?: Content;
          history?: Content;
          notableLocations?: Content;
      }
    | {
          _id: string;
          _type: 'writing';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          writingType?: 'myth' | 'poem' | 'story';
          defaultAttributes?: DefaultAttributes;
          information?: Information;
          description?: Content;
          content?: Content;
      }
>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
    interface SanityQueries {
        "*[ _type == 'documentSettings' ][0]{ information, informationCategories }": DocumentSettingsResult;
        '*[_type == $type && defaultAttributes.slug.current == $name][0]': SpecificTypePageQueryResult;
        '*[_type == $type && writingType == $writingType && defaultAttributes.slug.current == $name][0]': SpecificWritingTypePageQueryResult;
        '*[_type == $type && defined(defaultAttributes.slug.current)]': AllProductsOfTypeResult;
        '*[_type == $type && writingType == $writingType && defined(defaultAttributes.slug.current) ]': AllWritingProductsOfTypeResult;
    }
}
